export enum Types {
  BRASH = 'BRASH',
  CANVAS = 'CANVAS',
  LINE = 'LINE',
  RECT = 'RECT',
  CIRCLE = 'CIRCLE',
  LOADIMAGES = 'LOADIMAGES',
  LOADUSERS = 'LOADUSERS',
  EMAILFILTER = 'EMAILFILTER',
}
